name: ${pa_name}
author: ${pa_author}
version: ${pa_version}
description: ${pa_desc}
website: ${pa_source}
issue-url: ${pa_issues}
main: ${pa_group}.spigot.${pa_name}Spigot
api-version: 1.18
depend: [CommandAPI]