subprojects {
    apply plugin: 'java'

    archivesBaseName = "pixelartisan-${project.name}"
    group = 'fr.metouais.pixelartisan'
    version = '0.5.0-SNAPSHOT'

    repositories {
        mavenCentral()
        maven { url = 'https://hub.spigotmc.org/nexus/content/repositories/snapshots/' }
    }
    dependencies {
        implementation 'org.jetbrains:annotations:24.0.1'
        implementation 'org.slf4j:slf4j-api:2.0.17'
    }
}
