ext {
    pa_id = 'pixelartisan'
    pa_name = 'PixelArtisan'
    pa_desc = 'a plugin/mod for creating pixel art from images'
    pa_author = 'M_EtOuais'
    pa_version = '0.5.0-SNAPSHOT'
    pa_group = 'fr.metouais.'+pa_id
    pa_source = 'https://github.com/Carlier-Maxime/PixelArtisan'
    pa_website = pa_source
    pa_issues = pa_source+'/issues'
}

subprojects {
    apply plugin: 'java'

    archivesBaseName = "pixelartisan-${project.name}"
    group = rootProject.ext.pa_group
    version = rootProject.ext.pa_version

    repositories {
        mavenCentral()
        maven { url = 'https://hub.spigotmc.org/nexus/content/repositories/snapshots/' }
    }
    dependencies {
        implementation 'org.jetbrains:annotations:24.0.1'
        implementation 'org.slf4j:slf4j-api:2.0.17'
    }
}
