plugins {
    id 'java'
}

dependencies {
    implementation 'com.google.code.gson:gson:2.12.1'
}

def infoTemplate = file("src/main/java/fr/metouais/pixelartisan/common/utils/Info.java.in")
def infoOutput = file("build/generated/sources/info/java/fr/metouais/pixelartisan/common/utils/Info.java")

task generateInfo {
    inputs.file(infoTemplate)
    outputs.file(infoOutput)

    doLast {
        def content = infoTemplate.text
        project.properties.each { key, value ->
            content = content.replaceAll("@${key}@", value.toString())
        }
        infoOutput.parentFile.mkdirs()
        infoOutput.text = content
    }
}

compileJava.dependsOn(generateInfo)

sourceSets.main.java.srcDirs += 'build/generated/sources/info/java'